import './globals.css'
import Footer from '../components/Footer.js'
import RightSideForm from '@/components/RightSideForm'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <div className="mainclasss">
        <div>{children}</div>
        <div>  <RightSideForm/></div>
        <style>
          {`
            .mainclasss{
              display: grid;
              grid-template-columns: 7fr 5fr;
              padding: 20px 30px;
            }
          `}
        </style>
      </div>
      
     
      <br/>
      <Footer/>
      </body>
    </html>
  )
}
